
import React from 'react';
import { ResultData } from '../types';
import Spinner from './Spinner';
import { SparklesIcon } from './icons';

interface ResultDisplayProps {
  isLoading: boolean;
  result: ResultData | null;
}

const WelcomeMessage: React.FC = () => (
    <div className="text-center text-gray-400 flex flex-col items-center justify-center h-full gap-4">
        <SparklesIcon className="w-16 h-16 text-purple-500"/>
        <h2 className="text-2xl font-bold text-gray-300">Welcome to the Creative Suite</h2>
        <p className="max-w-md">Select a mode and enter a prompt below to get started. Let your creativity flow!</p>
    </div>
);


const ResultDisplay: React.FC<ResultDisplayProps> = ({ isLoading, result }) => {
  if (isLoading) {
    return <div className="flex justify-center items-center h-full"><Spinner /></div>;
  }

  if (!result) {
    return <WelcomeMessage />;
  }

  return (
    <div className="max-w-4xl mx-auto w-full animate-fade-in">
      {result.type === 'image' && (
        <div className="p-4 bg-black/20 rounded-lg">
          <img
            src={`data:image/png;base64,${result.content}`}
            alt="Generated by Gemini"
            className="w-full max-w-lg mx-auto rounded-md shadow-2xl"
          />
        </div>
      )}
      {result.type === 'text' && (
        <div className="bg-gray-800 p-4 sm:p-6 rounded-lg shadow-inner">
          <p className="text-gray-200 whitespace-pre-wrap leading-relaxed">{result.content}</p>
        </div>
      )}
      {result.type === 'error' && (
        <div className="bg-red-900/50 border border-red-700 p-4 rounded-lg">
          <h3 className="font-bold text-red-300 mb-2">An Error Occurred</h3>
          <p className="text-red-400">{result.content}</p>
        </div>
      )}
    </div>
  );
};

export default ResultDisplay;
